global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3000']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3001']